"$schema" = "https://starship.rs/config-schema.json"
format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$package\
$bun\
$gradle\
$nodejs\
$dotnet\
$golang\
$java\
$kotlin\
$lua\
$python\
$rust\
$swift\
$line_break\
$character"""
palette = "raks"
add_newline = false

[username]
format = "[@$user]($style) in "
style_root = "atomic_purple"
style_user = "atomic_purple"
show_always = true

[directory]
format = "[$path]($style) "
style = "atomic_violet"

[directory.substitutions]
"C:" = "Local"
"D:" = "Data"

[git_branch]
format = "on [$symbol $branch]($style) "
symbol = "ğŸªµ"
style = "#d69956"

[git_commit]
format = "on [$tag]($style) "
style = "#da2d2b"
tag_symbol = "ğŸ”– "
tag_disabled = false

[git_status]
style = "atomic_purple"

[character]
success_symbol = "[â¯](bold yellow)"

[fill]
symbol = " "

[package]
format = "[$symbol ($version)]($style) "
symbol = "ğŸ“¦"
style = "#e0b56e"
display_private = true

[bun]
format = "[$symbol ($version)]($style) "
symbol = "ğŸ"
style = "#e0c393"

[gradle]
format = "[$symbol ($version)]($style) "
symbol = "ğŸ˜"
style = "#bababa"

[nodejs]
format = "[$symbol ($version)]($style) "
symbol = "ğŸ€"
style = "#02b95e"

[dotnet]
format = "[$symbol ($version)]($style) "
symbol = "ğŸ¯"
style = "#3f91dc"

[golang]
format = "[$symbol ($version)]($style) "
symbol = "ğŸ¹"
style = "#d69956"

[java]
format = "[$symbol ($version)]($style) "
symbol = "â˜•"
style = "#7d4533"

[kotlin]
format = "[$symbol ($version)]($style) "
symbol = "ğŸ«§"
style = "#c599da"

[lua]
format = "[$symbol ($version)]($style) "
symbol = "ğŸŒ™"
style = "#ddbb39"

[python]
format = "[$symbol ($version)]($style) "
symbol = "ğŸ"
style = "#02b95e"

[rust]
format = "[$symbol ($version)]($style) "
symbol = "ğŸ¦€"
style = "#da2d2b"

[swift]
format = "[$symbol ($version)]($style) "
symbol = "ğŸ¦"
style = "#b20c42"

[palettes.raks]
atomic_purple = "#ce3ed6"
atomic_violet = "#c698f2"
